[package]
name = "texo-ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { path = "../dioxus/packages/dioxus", features = ["desktop"]}
tween ={ version = "2.0.2", default-features = false, features = ["libm"]}
async-std = {version="1.12.0", features = ["unstable"]}
manganis = { git = "https://github.com/DioxusLabs/collect-assets", rev = "e0093a4" }
log = "0.4.20"


[dev-dependencies]
dioxus-web = {path = "../dioxus/packages/web"}
# dioxus-desktop = { path = "../dioxus/packages/desktop"}
log = "0.4.20"
dioxus-logger = "0.4.1"
